### ISSUE TITLE
Batch Email Endpoint Support

### ISSUE THREAD

**Issue by lucas-allydvm** [kickboxio/kickbox-ruby#17]
Hi,

Your service allows for batch email verification. https://docs.kickbox.com/docs/batch-verification-api, but that's not in the ruby gem. It would be awesome if you could add this feature here. I made a PR with the work already. Thanks

https://github.com/kickboxio/kickbox-ruby/pull/16

**Comment by danhstevens** [comment]
Merged. Thanks so much!!
