### ISSUE TITLE
kickbox installation error

### ISSUE THREAD

**Issue by kevin-jj** [kickboxio/kickbox-ruby#3]
We tried to install kickbox gem using bundle install command and got some error message.

Bundler could not find compatible versions for gem "faraday":
  In Gemfile:
    kickbox (>= 0) ruby depends on
      faraday (~> 0.8.8) ruby

    omniauth-facebook (>= 0) ruby depends on
      omniauth-oauth2 (~> 1.2) ruby depends on
        faraday (0.9.0)

**Comment by schaitanya** [comment]
Fixed at #7
